### ISSUE TITLE
Add option to retrieve cookies as well as saved logins

### ISSUE THREAD

**Issue by br-sn** [login-securite/DonPAPI#16]
DonPAPI does a fantastic job of retrieving saved login credentials, however the option to retrieve cookies would be beneficial to be able to steal existing sessions and bypass 2FA protection. Currently it seems an attempt was made at adding this feature but it may have been abandoned (https://github.com/login-securite/DonPAPI/blob/main/myseatbelt.py#L460). I might try and have a go at this in a few weeks but not sure if I'll be able to pull it off.

**Comment by login-securite** [comment]
donne in PR cookies_enabled for chrome cookies. 
will have to research a bit to do this for IE/EDGE/Firefox too
