### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by idanlivni** [login-securite/DonPAPI#25]
Hi, 

This project looks amazing and solves a large amount of possible problems, However looking at the codebase I wasn't able to find a LICENSE file, 
The only thing I could find is a message in the master file indicating the license is a modified version of Apache license with more details in the LICENSE file that I wasn't able to find. 

# This software is provided under under a slightly modified version
# of the Apache Software License. See the accompanying LICENSE file
# for more information.

If a license file could be added it will be great help !

**Comment by noraj** [comment]
Please set up a license https://choosealicense.com/no-permission/

**Comment by Zeecka** [comment]
Issue can be closed (see https://github.com/login-securite/DonPAPI/commit/9b731b4eba642542d3feafdecea1ce05b4b3450c)
