### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by no0neismrji** [login-securite/DonPAPI#39]
Bonjour à tous, ça fait un p'tit moment que j'utilise DonPAPI et depuis une fresh install de Kali j'ai une erreur que je n'arrive pas debbugger si quelqu'un a une idée je suis preneur: 

# python3 DonPAPI.py                        
Traceback (most recent call last):
  File "DonPAPI.py", line 27, in <module>
    from myseatbelt import MySeatBelt
  File "myseatbelt.py", line 12, in <module>
    from lib.secretsdump import LSASecrets as MyLSASecrets
ModuleNotFoundError: No module named 'lib.secretsdump'

Alors que la lib est bien dispo dasn e dossier d'installation dans lib/secretsdump 
Pour être sûr de moi j'avais ajouté le chemin d'exécution dans la variable $PATH, mais rien n'y fait.

Je n'ai aucune idée de comment debbugger ceci.

D'avance merci de l'attention porté à mon problème !

**Comment by corsch** [comment]
I have the same issue, can you tell me how you fixed it?

**Comment by shaaati** [comment]
I am not experienced with Python development, nor do I know what a best practice setup would look like.

However, I found that you can make it work by adding an empty `__init__.py` file to the lib folder.

As far as I understand https://stackoverflow.com/questions/448271 this should be old behaviour not needed with Python 3.3 and newer, but it worked for my Kali setup, which is running Python 3.10.9.
