### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.secretsdump'

### ISSUE THREAD

**Issue by no0neismrji** [login-securite/DonPAPI#45]
Hi everyone, 

For some time now, I have been facing an error that I don't understand and that I can't solve, 
I am Kali Linux : 

`$ uname -a                                            [10/03/23 | 9:22:47]
Linux no0ne-kali 6.1.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.12-1kali2 (2023-02-23) x86_64 GNU/Linux
`

I use the version of python 3.11.2 : 

`$ python3                                             [10/03/23 | 9:20:59]
Python 3.11.2 (main, Feb 12 2023, 00:48:52) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
`

I proceeded to the installation of DonPAPI as explained on the Git but here, impossible to make it work: 

`$ python3 DonPAPI.py                                  [10/03/23 | 9:30:04]
Traceback (most recent call last):
  File "/home/no0ne/DonPAPI/DonPAPI.py", line 27, in <module>
    from myseatbelt import MySeatBelt
  File "/home/no0ne/DonPAPI/myseatbelt.py", line 12, in <module>
    from lib.secretsdump import LSASecrets as MyLSASecrets
ModuleNotFoundError: No module named 'lib.secretsdump'
`

So I looked if the secretsdump module is present in the install directory :

`$ ls DonPAPI/lib                                              [10/03/23 | 9:21:32]
adconnect.py            dpapi_pick  neo4jconnection.py  secretsdump.py
certificates.py         dpapi.py    new_module.py       toolbox.py
compliance_security.py  eater.py    RecentFiles.py      wmi.py
defines.py              fileops.py  reg.py
`

I don't have any explanation why it doesn't work, if anyone has an idea I'm interested.

For those who will take the time, thank you in advance.

**Comment by samoonaski** [comment]
Try with Python 3.10. It's not working with python3.11

**Comment by no0neismrji** [comment]
Ty for your time i will try this if i see this error again !

**Comment by no0neismrji** [comment]
Ty for your time i will try this if i see this error again 

(I had to reinstall my OS)
