### ISSUE TITLE
ERROR derivekey exception : can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by BZHuntShampu** [login-securite/DonPAPI#53]
Hello there,

When running DonPAPI with an admin user I get the following error repeated many times :
`ERROR derivekey exception : can only concatenate str (not "bytes") to str`

The command I'm running is :
`DonPAPI -H <HASH> <DOMAIN>/<USER>@<TARGET>` (_redacted for privacy_)

Tested on Kali Linux with Python 3.10.10

**Comment by BZHuntShampu** [comment]
I was able to fix it with a slight modification of the code
I will create a PR for this

**Comment by login-securite** [comment]
Closing since the PR was merged
