### ISSUE TITLE
HTML report (-R) markup inconsistency & optimization

### ISSUE THREAD

**Issue by Zeecka** [login-securite/DonPAPI#55]
HTML reports have inconsistency (missing closing markup, no coherence with lowercase/uppercase, ...) and can be optimized (for instance: `<a class="firstletter">H</a><a>ostname</A>` can be replaced with `<p>Hostname</p>` using the CSS selector [`::first-letter`](https://developer.mozilla.org/en-US/docs/Web/CSS/::first-letter)).

I'd like to work on the [generate_report()](https://github.com/login-securite/DonPAPI/blob/fb87978fb8303ceab84b32920c0bf380494748e3/donpapi/database.py#L30) function, using [Jinja](https://palletsprojects.com/p/jinja/) templating. Is it worth having a try and are you looking for a PR on this feature (report content won't change, only a refactoring) ?

**Comment by zblurx** [comment]
Hey, it would be great 😁

**Comment by Zeecka** [comment]
I'm currently working on refactoring database.py (PEP-8 compliant, ...), then I'll start reworking on the HTML rendering.
I do not have an exhaustive lab to test DonPAPI. Can you provide a VM or better, a sqlite3 database with credentials so I can interface with ?

**Comment by zblurx** [comment]
Actually I do not have an exhaustive lab either, as DonPAPI is collecting a looot of stuff.

**Comment by zblurx** [comment]
Closing since no report anymore
