### ISSUE TITLE
Microsoft Edge support

### ISSUE THREAD

**Issue by iamauser123xd** [login-securite/DonPAPI#56]
DonPAPI is able to retrieve credentials for Chrome, there should be support for edge considering the large-scale use of edge within environments.

Edge is based of chromium so it shouldn't be hard at all to implement, user data is stored in %localappdata%\microsoft\edge\User Data\Default

**Comment by zblurx** [comment]
Hey, we are currently implementing #40, so it will be available soon.

**Comment by zblurx** [comment]
Added with 1523495490d221a3f003fb1ad03e2ec70dc20834
