### ISSUE TITLE
Truncated DDC2 hash in HTML report

### ISSUE THREAD

**Issue by psyray** [login-securite/DonPAPI#68]
I noticed that DCC2 hash are truncated in the HTML report
![image](https://github.com/login-securite/DonPAPI/assets/1230954/9dd899c6-5955-42f8-b906-23a04914c4e8)

![image](https://github.com/login-securite/DonPAPI/assets/1230954/bfb6c43b-689f-40a8-80b7-73e766ef30e2)

Is it normal ?

**Comment by zblurx** [comment]
No report anymore. Closing
